[versions]
datetime = "0.8.0"
browser = "0.5.0"
serialization = "1.11.0"
maplibre = "0.14.0"

[libraries]
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
kotlinx-browswer = { group = "org.jetbrains.kotlinx", name = "kotlinx-browser", version.ref = "browser" }
kotlinx-serialization-xml = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-xml", version.ref = "serialization" }
maplibre-compose = { group = "org.maplibre.compose", name = "maplibre-compose", version.ref = "maplibre" }

[bundles]
